### ISSUE TITLE
Misspell

### ISSUE THREAD

**Issue by Karaoke4272** [nickquednow/operation-hospital-roundup#1]
Misspelled "John" in Readme. 
Hi.

**Comment by nickquednow** [comment]
Hello @Karaoke4272. The readme was specifically done that way so the name would not be an actual person (hopefully) due to the fact that I do not want anyone named John thinking that they were meant to be in a hospital, ut if you wish you can think of their name as "J-Hon" to avoid confusion from anyone's real name.

**Comment by Karaoke4272** [comment]
Ah, okay. My bad.
